### ISSUE TITLE
Program outputs an error

### ISSUE THREAD

**Issue by SMKamrulHasan** [utkuozbulak/pytorch-cnn-adversarial-attacks#1]
Iteration: 0
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-14-44bc27027cea> in <module>()
----> 1 FGS_untargeted.generate(original_image, org_class, target_class)

<ipython-input-12-f128d7e73534> in generate(self, original_image, org_class, target_class)
     48             out = self.model(processed_image)
     49             # Calculate CE loss
---> 50             pred_loss = ce_loss(out, im_label_as_var)
     51             # Do backward pass
     52             pred_loss.backward()

~\anaconda3\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    475             result = self._slow_forward(*input, **kwargs)
    476         else:
--> 477             result = self.forward(*input, **kwargs)
    478         for hook in self._forward_hooks.values():
    479             hook_result = hook(self, input, result)

~\anaconda3\lib\site-packages\torch\nn\modules\loss.py in forward(self, input, target)
    860     def forward(self, input, target):
    861         return F.cross_entropy(input, target, weight=self.weight,
--> 862                                ignore_index=self.ignore_index, reduction=self.reduction)
    863 
    864 

~\anaconda3\lib\site-packages\torch\nn\functional.py in cross_entropy(input, target, weight, size_average, ignore_index, reduce, reduction)
   1548     if size_average is not None or reduce is not None:
   1549         reduction = _Reduction.legacy_get_string(size_average, reduce)
-> 1550     return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
   1551 
   1552 

~\anaconda3\lib\site-packages\torch\nn\functional.py in nll_loss(input, target, weight, size_average, ignore_index, reduce, reduction)
   1405                          .format(input.size(0), target.size(0)))
   1406     if dim == 2:
-> 1407         return torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
   1408     elif dim == 4:
   1409         return torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)

RuntimeError: Expected object of type torch.LongTensor but found type torch.IntTensor for argument #2 'target'

**Comment by SMKamrulHasan** [comment]
Solved the problem by updating long() 
im_label_as_var = Variable(torch.from_numpy(np.asarray([target_class]))).long()

Thanks

**Comment by SMKamrulHasan** [comment]
But why the program does not work for different example like "space shuttle" from image net?

**Comment by utkuozbulak** [comment]
Hello, 

> But why the program does not work for different example like "space shuttle" from image net?

It should. As for the other errors, I coded all these in a prior version of Pytorch and I should really spend some time to update it to the latest version.

**Comment by SMKamrulHasan** [comment]
What is the target example input?

**Comment by utkuozbulak** [comment]
Have a look at get_params function at misc_functions.
